-- Live optical pulse ingestion (first prototype milestone).
--
-- A physical optical reader (Kamstrup OMNIPOWER LED -> LDR/phototransistor ->
-- Arduino/ESP32 -> HTTPS) reports raw pulse events into NewinMeter. This is
-- deliberately kept in its OWN tables, completely separate from the LiveMopay
-- ledger (energy_rows, *_rollups, dashboard_summary): the optical feed is live
-- telemetry for consumption LiveMopay will only report later, so merging the
-- two now would double-count. Reconciliation/overlay is intentionally deferred.
--
-- Both tables follow the same access model as livemopay_connections and
-- push_subscriptions: service-role only, RLS enabled with no anon/authenticated
-- policies. Devices authenticate with their own revocable key in the
-- /api/live/pulses route handler (never a Supabase key or user session), and
-- api_key_hash must never be enumerable from the browser. Owner reads, if ever
-- added, will go through future authenticated API routes that resolve
-- ownership via public.owns_livemopay_connection(connection_id) -- the smaller
-- secure scope is chosen here on purpose.

-- A physical measuring device, owned (transitively) by the user through their
-- LiveMopay connection. Only the SHA-256 hash of the device key is stored --
-- the raw key is shown once at creation and never persisted or logged. SHA-256
-- (not a slow password hash) is appropriate because the key is a high-entropy
-- random API token, not a human-chosen password.
create table public.meter_devices (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null references public.livemopay_connections(id) on delete cascade,
  name text not null,
  api_key_hash text not null unique,
  -- Harmless identifier only (e.g. the last few characters of the raw key) so
  -- a device can be recognised in a list without exposing anything secret.
  key_hint text,
  enabled boolean not null default true,
  pulses_per_kwh integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz,
  constraint meter_devices_name_not_empty check (length(btrim(name)) > 0),
  constraint meter_devices_pulses_per_kwh_positive check (pulses_per_kwh > 0)
);

create index meter_devices_connection_id_idx on public.meter_devices (connection_id);

-- Raw pulse telemetry. One row per LED flash (1 pulse = 1 Wh on this meter),
-- stored verbatim: NO derived watts/kWh/cost/tariff here, so calculations can
-- change later without reflashing hardware or rewriting history.
--
-- boot_id identifies one boot/session of the measuring hardware; seq is
-- monotonic within that boot. The (device_id, boot_id, seq) unique constraint
-- is what makes HTTP retries idempotent: replaying an identical batch inserts
-- nothing new. A new boot_id resets the seq namespace, so the same seq under a
-- different boot (or a different device) is a legitimately distinct row.
create table public.meter_pulses (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.meter_devices(id) on delete cascade,
  boot_id uuid not null,
  seq bigint not null,
  observed_at timestamptz not null,
  uptime_ms bigint not null,
  delta_ms bigint,
  received_at timestamptz not null default now(),
  constraint meter_pulses_seq_non_negative check (seq >= 0),
  constraint meter_pulses_uptime_non_negative check (uptime_ms >= 0),
  constraint meter_pulses_delta_non_negative check (delta_ms is null or delta_ms >= 0),
  constraint meter_pulses_boot_seq_unique unique (device_id, boot_id, seq)
);

create index meter_pulses_device_observed_at_idx on public.meter_pulses (device_id, observed_at);

alter table public.meter_devices enable row level security;
alter table public.meter_pulses enable row level security;

-- Same rationale as livemopay_connections/push_subscriptions: these tables are
-- never read or written from the browser. meter_devices holds api_key_hash;
-- meter_pulses is written only by the service-role client in /api/live/pulses
-- after the device key authenticates. No anon/authenticated policies exist, so
-- both roles get zero access.
revoke all on public.meter_devices from anon, authenticated;
revoke all on public.meter_pulses from anon, authenticated;
